- name: Check testrig directory.
  stat:
    path: "{{ testrig_dir }}"
  register: testrig_folder

- name: "Delete directory if already exists"
  file:
    path: "{{ testrig_dir }}"
    state: absent
  when: testrig_folder.stat.exists == true

- name: Update maven repository with settings file
  copy:
    src: "{{ item }}"
    dest: "{{ maven_dir }}"
  with_fileglob:
    - "{{ utils_dir }}/settings.xml"

- name: Download and Unarchive Functional Test
  unarchive:
    src: "https://github.com/mosip/mosip-functional-tests/archive/{{ testrig_version }}.zip"
    dest: "{{ tools_dir }}"
    remote_src: yes

#- name: Move versioned testrig to generic dir
#  command: "mv {{ tools_dir }}/mosip-functional-tests-{{ testrig_version }} {{ testrig_dir }}"

- name: Bulding partner demo service for dependency
  shell: "cd {{ testrig_dir }}/authentication-partnerdemo-service/ && mvn clean install"

- name: Bulding test-rig
  shell: "cd {{ testrig_dir }}/automationtests && mvn clean install"

- name: Copy jar file to test testrig directory
  command: "mv {{ testrig_dir }}/automationtests/target/*dependencies.jar {{ testrig_dir }}/automationtests.jar"
