# This play start the functional test and start scanning of API. Here we have split tasks and roles into seperate
# play as tasks only run after roles if they are in the same play (for some reason)
# and for us sequencing is important.

- hosts: security-console
  gather_facts: true
  tasks:
    - {name: 'Create report folder', file: {name: "{{ zap_report_dir }}", state: directory}}

- hosts: security-console
  gather_facts: true
  roles:
    - {role: api-scanning, tags: [api-scanning]}