# This play perform all the tasks needed for docker security scanning.
# Here we have split tasks and roles into seperate
# play as tasks only run after roles if they are in the same play (for some reason)
# and for us sequencing is important.

- hosts: security-console
  gather_facts: true
  tasks:
    - {name: 'Create docker bench security report folder', file: {name: "{{ dbs_report_dir }}", state: directory}}

- hosts: scancluster
  gather_facts: true
  become_user: root
  become: yes
  roles:
    - {role: docker-security/scanning, tags: [scanning]}
    - {role: docker-security/reporting, tags: [reporting]}
