# This play install all the tools needed on the security console for
# further execution of automation. Here we have split tasks and roles into seperate
# play as tasks only run after roles if they are in the same play (for some reason)
# and for us sequencing is important.

- hosts: security-console
  gather_facts: true 
  tasks:
    - {name: 'Create tmp folder', file: {name: "{{tmp_dir}}", state: directory}}
    - {name: 'Create logs folder', file: {name: "{{logs_dir}}", state: directory}}
    - {name: 'Create tools folder', file: {name: "{{tools_dir}}", state: directory}}

- hosts: security-console
  gather_facts: true
  roles:
    - {role: packages/python, tags: [python]} # Needed for letsencrypt and test scripts
    - {role: packages/pip, tags: [pip]}
    - {role: packages/pip-packages, tags: [pip-packages]}
    - {role: packages/copy-python-libs, tags: [copy-python-libs]}
    - {role: packages/zap-download, tags: [zap-download]}
    - {role: packages/maven, tags: [maven]}
    - {role: packages/functional-test, tags: [functional-test]}