- name: Check zap directory.
  stat:
    path: "{{ tools_dir }}/zap"
  register: zap_folder

- name: Download and Unarchive zap
  unarchive:
    src: https://github.com/zaproxy/zaproxy/releases/download/v2.9.0/ZAP_2.9.0_Linux.tar.gz
    dest: "{{ tools_dir }}"
    mode: 0755
    remote_src: yes
  when: zap_folder.stat.exists == false

- name: Move Zap to zap folder
  command: "mv {{ tools_dir }}/ZAP_2.9.0 {{ tools_dir }}/zap"
