
---
# Global variables - accessed by different roles and plays
#
tmp_dir: '/tmp/'
logs_dir: '/tmp/'

reporting_user: 'mosipdocs@gmail.com'
reporting_user_secret: ''

install_dir: '/home/mosipuser/mosip-security/mosip-security-playbook/'
roles_dir: '{{install_dir}}/roles'
utils_dir: '{{install_dir}}/utils'
lib_dir: '{{install_dir}}/utils/python-lib'
python_lib-dir: '/./usr/local/lib/python2.7/dist-packages/'
