
---
# Global variables - accessed by different roles and plays
#
tmp_dir: '/tmp/'
logs_dir: '/tmp/'

reporting_user: 'mosipdocs@gmail.com'
reporting_user_secret: ''

install_dir: '/home/mosipuser/mosip-security/mosip-security-playbook/'
#charts_root: '{{install_root}}/helm/charts'  # Helm charts root
roles_dir: '{{install_dir}}/roles'
utils_dir: '{{install_dir}}/utils'