- name: Download and Unarchive Functional Test
  unarchive:
    src: "https://github.com/mosip/mosip-functional-tests/archive/{{ testrig_version }}.zip"
    dest: "{{ tools_dir }}"
    remote_src: yes

- name: Move version to generic dir
  command: "mv {{ tools_dir }}/mosip-functional-tests-{{ testrig_version }} {{ tools_dir }}/testrig"

#- name: bulding test-rig
#  shell: "cd {{ tools_dir }}testrig/automationtests && mvn clean install"
