- name: Install apt packages
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
    with_items:
      - python
      - python-pip
      - libssl-dev
      - libcurl4-openssl-dev
      - python-dev
      - maven
  become: yes