- name: Install apt packages
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - libssl-dev
    - libcurl4-openssl-dev
    - python-dev
    - maven
    - libopenscap8
    - ssg-base
    - ssg-debderived
    - ssg-debian
    - ssg-nondebian
    - ssg-applications
  become: yes